source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from accounts.views import register_view, UserDetailView, UserListView, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', register_view, name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('accounts/', UserListView.as_view(), name='user_list'),
    path('<int:pk>/change/', UserChangeView.as_view(), name='change'),
    path('<int:pk>/password_change', UserPasswordChangeView.as_view(), name='password_change'),
]

source/to_do_list/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import IndexView, TaskView, TaskUpdateView, TaskDeleteView, ProjectListView, \
    ProjectView, ProjectCreateView, ProjectUpdateView, ProjectDeleteView, ProjectTaskCreateView, ProjectUserView

app_name = 'webapp'

urlpatterns = [
    path('tasks', IndexView.as_view(), name='index'),
    path('task/<int:pk>/', TaskView.as_view(), name='task_view'),
    path('task/<int:pk>/update/', TaskUpdateView.as_view(), name='task_update'),
    path('task/<int:pk>/delete/', TaskDeleteView.as_view(), name='task_delete'),
    path('', ProjectListView.as_view(), name='project_list'),
    path('project/<int:pk>/', ProjectView.as_view(), name='project_view'),
    path('project/add/', ProjectCreateView.as_view(), name='project_create'),
    path('project/<int:pk>/update/', ProjectUpdateView.as_view(), name='project_update'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('project/<int:pk>/tasks/add', ProjectTaskCreateView.as_view(), name='task_create'),
    path('project/<int:pk>/user/', ProjectUserView.as_view(), name='project_user'),
]

source/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth import get_user_model

class Profile(models.Model):
    user: AbstractUser = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE, verbose_name='Пользователь')
    user_info = models.TextField(null=True, blank=True, verbose_name='О себе')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')
    profile = models.URLField(null=True, blank=True, verbose_name='Профиль ссылка')

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'
        permissions = {("can_view_user_list", "Can view the list of users"),}

source/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from accounts.models import Profile


class MyUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta(UserCreationForm.Meta):
        fields = ['username', 'password1', 'password2',
                  'first_name', 'last_name', 'email']

    def clean(self):
        cleaned_data = super().clean()
        errors = []
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        if not (first_name or last_name):
            errors.append(ValidationError("Required field"))
        if errors:
            raise ValidationError(errors)
        return cleaned_data


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']
        

class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm, PasswordChangeForm
from django.views.generic import DetailView, ListView, UpdateView
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin

from .models import Profile


def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            context['has_error'] = True
    return render(request, 'registration/login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('index')


def register_view(request, *args, **kwargs):
    if request.method == 'POST':
        form = MyUserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user).save()
            login(request, user)
            return redirect('webapp:index')
    else:
        form = MyUserCreationForm()
    return render(request, 'user_create.html', context={'form': form})


class UserDetailView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'


class UserListView(PermissionRequiredMixin,ListView):
    template_name = 'user_list.html'
    context_object_name = 'users'
    paginate_by = 5
    permission_required = 'accounts.can_view_user_list'

    def get_context_data(self,*, object_list=None, **kwargs):
        return super().get_context_data(object_list=object_list,**kwargs)

    def get_queryset(self):
        data = User.objects.all()
        return data

class UserChangeView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'


    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        profile_form = self.get_profile_form()
        form = self.get_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        form.save()
        profile_form.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)


    def test_func(self):
        return self.get_object().pk == self.request.user.pk

class UserPasswordChangeView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    template_name = 'user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def get_success_url(self):
        return reverse('accounts:login')

    def test_func(self):
        return self.get_object().pk == self.request.user.pk

source/accounts/templates/login.html
<h1>Вход</h1>
    <form action="{% url 'project_list' %}" method="post" class="text-center">
        {% csrf_token %}
        {% if has_error %}
            <p class="form-error">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input type="text" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Пароль:</label>
            <input type="password" name="password" id="password">
        </div>
        <button type="submit">Войти</button>
    </form>

source/accounts/templates/user_change.html
{% extends 'base.html' %}
{% block title %}Редактировать пользователя{% endblock %}
{% block menu %}
    <li><a href="{% url "accounts:detail" user_obj.pk %}">Назад</a></li>
    <li><a href="{% url 'accounts:password_change' user_obj.pk %}">Смена пароля</a></li>
{% endblock %}

{% block content %}
    <h1>Поменять личные данные</h1>
    <form action="{% url 'accounts:change' user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partial/form.html' with form=form fields_only=True %}
        {% include 'partial/form.html' with form=profile_form fields_only=True %}
        <br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

source/accounts/templates/user_create.html
{% extends 'base.html' %}
{% block title %}Регистрация{% endblock %}

{% block content %}

    <h1>Регистрация</h1>

    {% include 'partial/form.html' with form_method='post' button_text="Зарегистрироваться" %}

{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}

{% block title %}Пользователь{% endblock %}

{% block menu_links %}
    <li><a href="{% url 'accounts:change' user_obj.pk %}">Редактировать</a></li>
    <li><a href="{% url "accounts:password_change" user_obj.pk %}">Смена пароля</a></li>
{% endblock %}

{% block content %}
    <h1>Личная страница пользователя {{ user_obj.get_full_name|default:user_obj.username }}</h1>
    {% if user_obj.profile.avatar %}
        <img class="avatar" src="{{ user_obj.profile.avatar.url }}" width="250" height="250" alt="user picture">
    {% endif %}
    <p>Имя пользователя: {{ user_obj.username }}</p>
    <p>Имя: {{ user_obj.first_name }}</p>
    <p>Фамилия: {{ user_obj.last_name }}</p>
    <p>О себе: {{ user_obj.profile.user_info }}</p>
    <p>Почта: {{ user_obj.email }}</p>
    <p>Ссылка: {{ user_obj.profile.profile }}</p>

    <h2 class="text-center clear">Список проектов, в которых участвует пользователь:</h2>
    {% include 'partial/project_list1.html' with projects=user_obj.projects.all %}
{% endblock %}

source/accounts/templates/user_list.html
{% extends 'base.html' %}

{% block content %}

   <h1>Accounts</h1>

   {% for user in users %}
        <h2><a href="{% url 'accounts:detail'  request.user.pk %}">{{ user.username}}</a></h2>
   {% endfor %}

{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}

{% block title %}Смена пароля{% endblock %}

{% block menu %}
    <li><a href="{% url "accounts:detail" user_obj.pk %}">Назад</a></li>
    <li><a href="{% url "accounts:change" user_obj.pk %}">Редактирование личных данных</a></li>
{% endblock %}

{% block content %}
    <h1>Смена пароля</h1>
    {% url "accounts:password_change" user_obj.pk as action_url %}
    {% include 'partial/form.html' with action_url=action_url form_method="post" %}
{% endblock %}